import csv
import os
import json

output_dir = r"C:\Users\ASUS\.gemini\antigravity\scratch"

def clean_data(data_list, key_field="CÓDIGO_NODO"):
    # Filter out empty rows generated by trailing semicolons in CSV
    return [r for r in data_list if r.get(key_field, "").strip() != ""]

def run():
    pext_raw = []
    with open(os.path.join(output_dir, "Prueba_BD_PEXT.csv"), "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=";")
        for row in reader: pext_raw.append(row)

    iao_raw = []
    with open(os.path.join(output_dir, "Prueba_BD_IAO.csv"), "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=";")
        for row in reader: iao_raw.append(row)

    pext_data = clean_data(pext_raw)
    iao_data = clean_data(iao_raw)

    # Unique lists for filters
    localidades = sorted(list(set([r["LOCALIDAD"] for r in pext_data if "LOCALIDAD" in r])))
    nodos = sorted(list(set([r["CÓDIGO_NODO"] for r in pext_data if "CÓDIGO_NODO" in r])))
    fechas = sorted(list(set([r["Fecha_Inicio"] for r in pext_data if "Fecha_Inicio" in r and r["Fecha_Inicio"].strip() != ""])))

    html_content = f"""<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FTTH Pronatel - Dashboard Directivo</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root {{
            --bg-color: #0f172a; --card-bg: rgba(30, 41, 59, 0.7); --card-border: rgba(255, 255, 255, 0.1);
            --text-primary: #f8fafc; --text-secondary: #94a3b8;
            --accent-1: #3b82f6; --accent-2: #10b981; --accent-3: #8b5cf6; --accent-warning: #f59e0b;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; font-family: 'Inter', sans-serif; }}
        body {{ background-color: var(--bg-color); color: var(--text-primary); min-height: 100vh; padding: 2rem; 
               background-image: radial-gradient(at 0% 0%, rgba(59,130,246,0.15) 0, transparent 50%), radial-gradient(at 100% 100%, rgba(139,92,246,0.15) 0, transparent 50%); background-attachment: fixed; }}
        
        .header {{ margin-bottom: 2rem; text-align: center; }}
        .header h1 {{ font-size: 2.2rem; font-weight: 800; background: linear-gradient(to right, #60a5fa, #a78bfa); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 1.5rem; }}
        
        .filters-panel {{ background: rgba(15, 23, 42, 0.6); border: 1px solid var(--card-border); border-radius: 1rem; padding: 1.5rem; max-width: 1400px; margin: 0 auto 2rem auto; display: flex; flex-wrap: wrap; gap: 1.5rem; justify-content: center; }}
        .filter-group {{ display: flex; flex-direction: column; gap: 0.5rem; }}
        .filter-group label {{ font-size: 0.85rem; font-weight: 600; color: var(--text-secondary); text-transform: uppercase; letter-spacing: 1px; }}
        select {{ background-color: rgba(30, 41, 59, 0.9); color: var(--text-primary); border: 1px solid var(--accent-1); padding: 0.6rem 1rem; border-radius: 0.5rem; font-size: 0.95rem; outline: none; cursor: pointer; min-width: 200px; }}
        select:focus {{ border-color: #60a5fa; box-shadow: 0 0 10px rgba(59,130,246,0.3); }}
        
        .subfilter-panel {{ background: rgba(245, 158, 11, 0.1); border: 1px solid rgba(245, 158, 11, 0.3); padding: 1rem; border-radius: 0.8rem; display: flex; align-items: center; gap: 1rem; width: 100%; justify-content: center; margin-top: 0.5rem; }}
        .subfilter-panel label {{ color: var(--accent-warning); }}
        .subfilter-panel select {{ border-color: var(--accent-warning); }}

        .dashboard-grid {{ display: grid; grid-template-columns: repeat(12, 1fr); gap: 1.5rem; max-width: 1400px; margin: 0 auto; }}
        .card {{ background: var(--card-bg); backdrop-filter: blur(12px); border: 1px solid var(--card-border); border-radius: 1rem; padding: 1.5rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }}
        .kpi-card {{ grid-column: span 4; text-align: center; }}
        @media (max-width: 1024px) {{ .kpi-card, .chart-container {{ grid-column: span 12 !important; }} }}
        
        .kpi-value {{ font-size: 2.8rem; font-weight: 800; margin: 0.5rem 0; color: var(--text-primary); }}
        .kpi-label {{ color: var(--text-secondary); font-size: 0.85rem; text-transform: uppercase; font-weight: 600; }}
        .kpi-1 .kpi-value {{ color: var(--accent-1); }} .kpi-2 .kpi-value {{ color: var(--accent-2); }} .kpi-3 .kpi-value {{ color: var(--accent-3); }}

        .chart-container {{ grid-column: span 4; min-height: 280px; display: flex; flex-direction: column; }}
        .chart-wrapper {{ position: relative; flex-grow: 1; height: 100%; min-height: 220px; }}
        .chart-title {{ font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem; color: var(--text-primary); text-align: center; border-bottom: 1px solid var(--card-border); padding-bottom: 0.5rem; }}

        .table-container {{ grid-column: span 12; overflow-x: auto; }}
        table {{ width: 100%; border-collapse: collapse; text-align: left; }}
        th, td {{ padding: 1rem; border-bottom: 1px solid var(--card-border); }}
        th {{ color: var(--accent-1); font-weight: 600; font-size: 0.9rem; text-transform: uppercase; }}
        td {{ color: var(--text-primary); font-size: 0.95rem; }}
        tr:hover td {{ background-color: rgba(255,255,255,0.05); }}
        .highlight-col {{ background-color: rgba(16, 185, 129, 0.1); font-weight: 600; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Centro de Control FTTH - Gilat/Pronatel</h1>
    </div>

    <!-- Panel de Filtros -->
    <div class="filters-panel">
        <div class="filter-group">
            <label>📍 Localidad</label>
            <select id="f_localidad" onchange="updateDashboard()"><option value="ALL">Todas las Localidades</option></select>
        </div>
        <div class="filter-group">
            <label>🏷️ Código Nodo</label>
            <select id="f_nodo" onchange="updateDashboard()"><option value="ALL">Todos los Nodos</option></select>
        </div>
        <div class="filter-group">
            <label>📅 Fecha de Inicio</label>
            <select id="f_fecha" onchange="updateDashboard()"><option value="ALL">Cualquier Fecha</option></select>
        </div>
        
        <div class="subfilter-panel">
            <label>🔍 Análisis Específico PEXT:</label>
            <select id="f_pext" onchange="updateDashboard()">
                <option value="ALL">Desactivado (Ver IAOs)</option>
                <option value="SPL_1X2">Splitter 1x2 (Cantidades)</option>
                <option value="SPL_1X4">Splitter 1x4 (Cantidades)</option>
                <option value="SPL_1X8">Splitter 1x8 (Cantidades)</option>
                <option value="POSTES_NUEVOS">Postes Nuevos (Cantidades e Izados)</option>
            </select>
        </div>
    </div>

    <div class="dashboard-grid">
        <!-- KPIs -->
        <div class="card kpi-card kpi-1"><div class="kpi-label">FO Desplegada</div><div class="kpi-value" id="valFO">0 <span style="font-size:1.2rem">m</span></div></div>
        <div class="card kpi-card kpi-2"><div class="kpi-label">IAOs Instaladas</div><div class="kpi-value" id="valIAO">0</div></div>
        <div class="card kpi-card kpi-3"><div class="kpi-label" id="lblKpi3">Postes Intervenidos</div><div class="kpi-value" id="valPostes">0</div></div>

        <!-- Charts -->
        <div class="card chart-container"><h2 class="chart-title">Tipos de IAO</h2><div class="chart-wrapper"><canvas id="chartTipos"></canvas></div></div>
        <div class="card chart-container"><h2 class="chart-title">Uso de Postes</h2><div class="chart-wrapper"><canvas id="chartPostes"></canvas></div></div>
        <div class="card chart-container"><h2 class="chart-title">IAOs por Cuadrilla</h2><div class="chart-wrapper"><canvas id="chartCuadrillas"></canvas></div></div>
        
        <!-- Progressive Disclosure Table -->
        <div class="card table-container">
            <h2 class="chart-title" id="tableTitle" style="text-align: left;">📋 Detalle de IAOs</h2>
            <table id="dataTable">
                <thead id="tableHead"></thead>
                <tbody id="tableBody"></tbody>
            </table>
        </div>
    </div>

    <script>
        const rawPext = {json.dumps(pext_data)};
        const rawIao = {json.dumps(iao_data)};
        
        // Poblar selects
        const locs = {json.dumps(localidades)};
        const nodos = {json.dumps(nodos)};
        const fechas = {json.dumps(fechas)};
        
        const selLoc = document.getElementById('f_localidad');
        locs.forEach(l => selLoc.add(new Option(l, l)));
        const selNodo = document.getElementById('f_nodo');
        nodos.forEach(n => selNodo.add(new Option(n, n)));
        const selFecha = document.getElementById('f_fecha');
        fechas.forEach(f => selFecha.add(new Option(f, f)));

        let cTipos, cPostes, cCuadrillas;

        function initCharts() {{
            cTipos = new Chart(document.getElementById('chartTipos'), {{ type: 'bar', data: {{ labels: [], datasets: [{{ data: [], backgroundColor: '#3b82f6', borderRadius: 4 }}] }}, options: {{ indexAxis: 'y', responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }}, scales: {{ x: {{ grid: {{ color: 'rgba(255,255,255,0.05)' }} }}, y: {{ grid: {{ display: false }} }} }} }} }});
            cPostes = new Chart(document.getElementById('chartPostes'), {{ type: 'doughnut', data: {{ labels: ["Nuevos", "Eléctricos", "Terceros"], datasets: [{{ data: [], backgroundColor: ['#10b981', '#3b82f6', '#f59e0b'], borderWidth: 0, cutout: '65%' }}] }}, options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ position: 'bottom', labels: {{ padding: 15, boxWidth: 12, color: '#f8fafc' }} }} }} }} }});
            cCuadrillas = new Chart(document.getElementById('chartCuadrillas'), {{ type: 'bar', data: {{ labels: [], datasets: [{{ data: [], backgroundColor: '#8b5cf6', borderRadius: 4 }}] }}, options: {{ responsive: true, maintainAspectRatio: false, plugins: {{ legend: {{ display: false }} }}, scales: {{ y: {{ grid: {{ color: 'rgba(255,255,255,0.05)' }} }}, x: {{ grid: {{ display: false }} }} }} }} }});
        }}

        function updateDashboard() {{
            const vLoc = selLoc.value;
            const vNodo = selNodo.value;
            const vFecha = selFecha.value;
            const vPext = document.getElementById('f_pext').value;

            // 1. Filtrar Base de Datos PEXT
            let fPext = rawPext.filter(d => {{
                return (vLoc === "ALL" || d.LOCALIDAD === vLoc) &&
                       (vNodo === "ALL" || d.CÓDIGO_NODO === vNodo) &&
                       (vFecha === "ALL" || d.Fecha_Inicio === vFecha);
            }});

            // 2. Aplicar Subfiltro PEXT a fPext
            if (vPext === "SPL_1X2") fPext = fPext.filter(d => parseInt(d.Splitter_1x2_Cant) > 0);
            if (vPext === "SPL_1X4") fPext = fPext.filter(d => parseInt(d.Splitter_1x4_Cant) > 0);
            if (vPext === "SPL_1X8") fPext = fPext.filter(d => parseInt(d.Splitter_1x8_Cant) > 0);
            if (vPext === "POSTES_NUEVOS") fPext = fPext.filter(d => parseInt(d.Cant_Postes_Nuevos) > 0);

            // Obtener lista de IDs/Nombres filtrados para IAO
            const allowedLocs = fPext.map(p => p.LOCALIDAD);
            let fIao = rawIao.filter(d => allowedLocs.includes(d.LOCALIDAD));

            // Calcular KPIs
            let totalFO = 0; let postesN = 0, postesE = 0, postesT = 0;
            fPext.forEach(p => {{
                let valFO = parseFloat(p.Metraje_Promedio_FO.replace('.', '').replace(',', '.'));
                if(!isNaN(valFO)) totalFO += valFO;
                postesN += parseInt(p.Cant_Postes_Nuevos) || 0;
                postesE += parseInt(p.Cant_Postes_Electricos_BT || 0) + parseInt(p.Cant_Postes_Electricos_MT || 0);
                postesT += parseInt(p.Cant_Postes_Terceros || 0); // Manejo por si no existe
            }});

            document.getElementById('valFO').innerHTML = totalFO.toLocaleString('en-US') + ' <span style="font-size:1.2rem">m</span>';
            document.getElementById('valIAO').innerText = fIao.length;
            
            if(vPext === "POSTES_NUEVOS") {{
                document.getElementById('lblKpi3').innerText = "Total Izados";
                let izados = 0; fPext.forEach(p => izados += parseInt(p.Izados_Postes_Nuevos) || 0);
                document.getElementById('valPostes').innerText = izados;
            }} else {{
                document.getElementById('lblKpi3').innerText = "Postes Intervenidos";
                document.getElementById('valPostes').innerText = (postesN + postesE + postesT);
            }}

            // Graficas
            let countTipos = {{}}; let countCuadrillas = {{}};
            fIao.forEach(i => {{
                countTipos[i.Tipo_IAO] = (countTipos[i.Tipo_IAO] || 0) + 1;
                countCuadrillas[i.CUADRILLA] = (countCuadrillas[i.CUADRILLA] || 0) + 1;
            }});

            cTipos.data.labels = Object.keys(countTipos); cTipos.data.datasets[0].data = Object.values(countTipos); cTipos.update();
            cPostes.data.datasets[0].data = [postesN, postesE, postesT]; cPostes.update();
            cCuadrillas.data.labels = Object.keys(countCuadrillas); cCuadrillas.data.datasets[0].data = Object.values(countCuadrillas); cCuadrillas.update();

            // Renderizar Tabla según Contexto
            const thead = document.getElementById('tableHead');
            const tbody = document.getElementById('tableBody');
            tbody.innerHTML = '';

            if (vPext === "ALL") {{
                document.getElementById('tableTitle').innerText = "📋 Detalle de IAOs";
                thead.innerHTML = `<tr><th>Código Nodo</th><th>Localidad</th><th>IAO</th><th>Tipo</th><th>Cuadrilla</th><th>Serie ONT</th><th>Aterramiento</th></tr>`;
                if(fIao.length === 0) tbody.innerHTML = '<tr><td colspan="7">No hay datos que coincidan con los filtros.</td></tr>';
                fIao.forEach(i => {{
                    tbody.innerHTML += `<tr><td>${{i.CÓDIGO_NODO}}</td><td>${{i.LOCALIDAD}}</td><td>${{i.CODIGO_IAO}}</td><td><span style="background:var(--accent-1); padding:2px 6px; border-radius:6px;">${{i.Tipo_IAO}}</span></td><td>${{i.CUADRILLA}}</td><td><code>${{i.Serie_Eq_1_ONT}}</code></td><td>${{i.Aterramiento_OK}}</td></tr>`;
                }});
            }} else if (vPext.startsWith("SPL_")) {{
                const tName = vPext.replace("SPL_", "Splitter ");
                document.getElementById('tableTitle').innerText = `📋 Localidades con ${{tName}}`;
                thead.innerHTML = `<tr><th>Código Nodo</th><th>Localidad</th><th>Cuadrilla PEXT</th><th>Spl 1x2</th><th>Spl 1x4</th><th>Spl 1x8</th><th>Observaciones</th></tr>`;
                if(fPext.length === 0) tbody.innerHTML = '<tr><td colspan="7">No hay localidades con este tipo de splitter.</td></tr>';
                fPext.forEach(p => {{
                    let c1x2 = p.Splitter_1x2_Cant || "0"; let c1x4 = p.Splitter_1x4_Cant || "0"; let c1x8 = p.Splitter_1x8_Cant || "0";
                    let hl1 = vPext==="SPL_1X2" ? "highlight-col" : ""; let hl4 = vPext==="SPL_1X4" ? "highlight-col" : ""; let hl8 = vPext==="SPL_1X8" ? "highlight-col" : "";
                    tbody.innerHTML += `<tr><td>${{p.CÓDIGO_NODO}}</td><td>${{p.LOCALIDAD}}</td><td>${{p.CUADRILLA}}</td><td class="${{hl1}}">${{c1x2}}</td><td class="${{hl4}}">${{c1x4}}</td><td class="${{hl8}}">${{c1x8}}</td><td>${{p.Observaciones}}</td></tr>`;
                }});
            }} else if (vPext === "POSTES_NUEVOS") {{
                document.getElementById('tableTitle').innerText = `📋 Avance de Postes Nuevos por Localidad`;
                thead.innerHTML = `<tr><th>Código Nodo</th><th>Localidad</th><th>Cuadrilla PEXT</th><th>Postes Nuevos Requeridos</th><th>Postes Izados</th><th>Avance %</th></tr>`;
                if(fPext.length === 0) tbody.innerHTML = '<tr><td colspan="6">No hay localidades con postes nuevos.</td></tr>';
                fPext.forEach(p => {{
                    let req = parseInt(p.Cant_Postes_Nuevos) || 0;
                    let iza = parseInt(p.Izados_Postes_Nuevos) || 0;
                    let pct = req > 0 ? Math.round((iza / req) * 100) : 0;
                    let clr = pct === 100 ? "color: var(--accent-2)" : (pct < 50 ? "color: #ef4444" : "color: var(--accent-warning)");
                    tbody.innerHTML += `<tr><td>${{p.CÓDIGO_NODO}}</td><td>${{p.LOCALIDAD}}</td><td>${{p.CUADRILLA}}</td><td class="highlight-col">${{req}}</td><td class="highlight-col">${{iza}}</td><td><strong style="${{clr}}">${{pct}}%</strong></td></tr>`;
                }});
            }}
        }}

        window.onload = function() {{ initCharts(); updateDashboard(); }};
    </script>
</body>
</html>
"""

    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_content)
    print("Dashboard HTML con filtros avanzados generado correctamente.")

if __name__ == "__main__":
    run()
